### ISSUE TITLE
osb and support for pgo 4.0.0

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/pgo-osb#21]
Hello,
Do you already know when you plan to upgrade the osb to support pgo 4.0.0

Regards,
José

**Comment by cahoonpwork** [comment]
We have started the process of upgrading osb to work with 4.0.0.  It should be available next week at the latest.

**Comment by jkatz** [comment]
The **pgo-osb** supports both v4.0.0 and v4.1.0 now!
