### ISSUE TITLE
Inconsistent authentication with postgres-operator API

### ISSUE THREAD

**Issue by tongpu** [CrunchyData/pgo-osb#26]
There's an inconsistency in the way pgo-osb authenticates with the postgres-operator API. In logic.go on line [160](https://github.com/CrunchyData/pgo-osb/blob/master/pkg/broker/logic.go#L160) the requests parameters are used for authentication, but on other lines (e.g. [179](https://github.com/CrunchyData/pgo-osb/blob/master/pkg/broker/logic.go#L179)) the command line parameters are being used for authentication with the postgres-operator API.

Please check which way should be the default one.

**Comment by jkatz** [comment]
This has been merged in and included in `v4.1.0`
