### ISSUE TITLE
Any known date for pgo-osb compatible with pgo 4.2?

### ISSUE THREAD

**Issue by ajoyej** [CrunchyData/pgo-osb#30]
Hello,

Do you know when osb for 4.2 will be available?

Thanks,
José

**Comment by jkatz** [comment]
Hi @ajoyej,

This is currently not high on our roadmap as we are focused on other parts of our PostgreSQL cloud enablement offerings. However, if you'd like to get on a call to discuss what you are looking to see, we'd be happy to do so. You can reach out at jonathan.katz@crunchydata.com

Thanks!

Jonathan

**Comment by jkatz** [comment]
Hi @ajoyej ,

I'm pleased to report that the pgo-osb is now compatible with v4.2.1!

https://github.com/CrunchyData/pgo-osb/releases/tag/v4.2.1

**Comment by ajoyej** [comment]
Great!
Thanks
José
