### ISSUE TITLE
Is osb 4.2.1 version compliant with the last pgo 4.4.0

### ISSUE THREAD

**Issue by obeyler** [CrunchyData/pgo-osb#32]
it seems that there is always a delta between pgo-osb version and pgo version
Do you still maintain osb or is it deprecated ?
Best regards

**Comment by jkatz** [comment]
@obeyler The short answer is no, 4.2.1 is not compatible with 4.4.0

However, I went ahead and updated the pgo-osb to be compatible with 4.4.0.

**Comment by jkatz** [comment]
@obeyler 4.4.1 is now available in DockerHub

**Comment by obeyler** [comment]
@jkatz Thanks !
