### ISSUE TITLE
Consider Operator-centric, Binding-centric integration with Service Catalog

### ISSUE THREAD

**Issue by ron1** [CrunchyData/pgo-osb#7]
The Service Catalog and Operator Framework have overlapping functionality. In order to minimize the overlap and avoid confusion, consider restricting the scope of the Service Catalog provision operation to simply deploying the Operator. In this case, the service catalog provision would accomplish the exact same function as the existing helm chart install/deploy. This is especially useful for OpenShift users since Helm is not supported out of the box in this environment.

Using this integration strategy, the Postgres Operator is used as documented to create/deploy postgres clusters and to create postgres users.

The Service Catalog bind operation accepts clustername and username parameters to identify the target cluster and user for the bind. This approach continues to leverage the Service Catalog ServiceBinding functionality to map the Postgres cluster/user credential to specific client application deployments.

So the Service Catalog provisions the Operator and binds client applications to the specific user of a specific cluster. The Operator, on the other hand, manages clusters and users as designed. This seems like a valid approach to making these two independent frameworks work together in a way that makes sense and leverages the strengths of each. Thoughts?

**Comment by jkatz** [comment]
I believe this is resolved in v4.1.0:

https://github.com/CrunchyData/pgo-osb/releases/tag/v4.1.0
