### ISSUE TITLE
Include optional database and user creation as part of ServiceBinding

### ISSUE THREAD

**Issue by ron1** [CrunchyData/pgo-osb#8]
A common developer-centric use case is to give multiple developers their own database on a shared PostgreSQL cluster. In order to support this use case, consider adding optional database and user name parameters to the ServiceBinding. During binding, the operator is used to create the database if it does not already exist. Likewise, the operator could be used to create the user and his/her secret if it does not already exist, and give ownership of the database to the user. During unbind, the secret is destroyed and optionally the user is deleted based on an unbind parameter. Another unbind parameter controls if the database should be deleted when the last user is removed.

**Comment by jkatz** [comment]
I believe this is working as intended in https://github.com/CrunchyData/pgo-osb/releases/tag/v4.1.0 but if not, please feel free to re-open.
